"""Synthetic Primavera P6 Master Schedule Data for Oil India Limited.

Models the full Work Breakdown Structure (WBS) from L1 to L6:
- L1: Project Level
- L2: Plant / Sub-Project Level
- L3: Discipline Level
- L4: Work Package / Area Level
- L5: Work Activity / Executable Phase
- L6: Micro-task / Executable Daily Action
"""

from datetime import datetime

SEED_TASKS = [
    # ================= L1: MACRO PROJECT =================
    {
        "id": "OIL-L1-01",
        "code": "OIL-EXP-2026",
        "level": "L1",
        "parent_id": None,
        "name": "Duliajan Central Gas Gathering & Compression Facility Expansion",
        "description": "Oil India Limited strategic natural gas gathering, processing, and high-pressure compression complex.",
        "discipline": "Project Management",
        "weight": 1.0,
        "planned_duration": 180,
        "actual_duration": 45,
        "planned_start": "2026-06-01",
        "planned_end": "2026-11-28",
        "progress_pct": 0.0,  # Computed via roll-up
        "status": "IN_PROGRESS",
    },

    # ================= L2: MAJOR SUB-PROJECTS =================
    {
        "id": "OIL-L2-01",
        "code": "GDU-03",
        "level": "L2",
        "parent_id": "OIL-L1-01",
        "name": "Gas Dehydration & Sweetening Unit-3",
        "description": "TEG absorption contactor towers, regenerators, and glycol circulation skid.",
        "discipline": "Piping & Mechanical",
        "weight": 0.40,
        "planned_duration": 120,
        "actual_duration": 35,
        "planned_start": "2026-06-15",
        "planned_end": "2026-10-15",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L2-02",
        "code": "FGCS-01",
        "level": "L2",
        "parent_id": "OIL-L1-01",
        "name": "Feed Gas High-Pressure Compressor Station",
        "description": "Centrifugal compressor trains C-101/102 with variable speed electric motor drives.",
        "discipline": "Piping & Mechanical",
        "weight": 0.45,
        "planned_duration": 140,
        "actual_duration": 40,
        "planned_start": "2026-06-01",
        "planned_end": "2026-10-20",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L2-03",
        "code": "UTIL-OFF",
        "level": "L2",
        "parent_id": "OIL-L1-01",
        "name": "Offsites, Flare & Utility Metering Complex",
        "description": "Substation-2, instrument air package, high pressure ground flare, and custody transfer skids.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.15,
        "planned_duration": 100,
        "actual_duration": 25,
        "planned_start": "2026-07-01",
        "planned_end": "2026-10-10",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },

    # ================= L3: DISCIPLINES (under FGCS-01 & GDU-03) =================
    {
        "id": "OIL-L3-01",
        "code": "FGCS-CIVIL",
        "level": "L3",
        "parent_id": "OIL-L2-02",
        "name": "Civil & Structural Foundations - Compressor Area",
        "description": "Excavation, piling, reinforced concrete compressor plinths, and steel superstructures.",
        "discipline": "Civil & Structural",
        "weight": 0.30,
        "planned_duration": 60,
        "actual_duration": 40,
        "planned_start": "2026-06-01",
        "planned_end": "2026-08-01",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L3-02",
        "code": "FGCS-PIPE",
        "level": "L3",
        "parent_id": "OIL-L2-02",
        "name": "Process Piping & Mechanical Erection - Compressor",
        "description": "Feed gas suction/discharge headers, lube oil skids, valves, and spool erection.",
        "discipline": "Piping & Mechanical",
        "weight": 0.45,
        "planned_duration": 80,
        "actual_duration": 30,
        "planned_start": "2026-07-01",
        "planned_end": "2026-09-20",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L3-03",
        "code": "FGCS-EI",
        "level": "L3",
        "parent_id": "OIL-L2-02",
        "name": "Electrical & Instrumentation - Compressor Bay",
        "description": "Cable tray routing, 11kV drive motors, vibration sensors, and ESD system wiring.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.25,
        "planned_duration": 65,
        "actual_duration": 15,
        "planned_start": "2026-07-15",
        "planned_end": "2026-09-20",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L3-04",
        "code": "GDU-PIPE",
        "level": "L3",
        "parent_id": "OIL-L2-01",
        "name": "Dehydration Process Piping & Vessel Erection",
        "description": "Contactor tower interconnection, glycol reboiler piping, and safety relief headers.",
        "discipline": "Piping & Mechanical",
        "weight": 0.60,
        "planned_duration": 75,
        "actual_duration": 20,
        "planned_start": "2026-06-20",
        "planned_end": "2026-09-05",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L3-05",
        "code": "GDU-CIVIL",
        "level": "L3",
        "parent_id": "OIL-L2-01",
        "name": "Civil Foundations - Glycol Unit",
        "description": "TEG contactor tower foundation, reboiler firewalls, and paving.",
        "discipline": "Civil & Structural",
        "weight": 0.40,
        "planned_duration": 50,
        "actual_duration": 35,
        "planned_start": "2026-06-15",
        "planned_end": "2026-08-05",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },

    # ================= L4: WORK PACKAGES =================
    {
        "id": "OIL-L4-01",
        "code": "WP-PLINTH-C101",
        "level": "L4",
        "parent_id": "OIL-L3-01",
        "name": "Compressor C-101 Equipment Plinth Foundation",
        "description": "Block foundation, anchor bolt sleeves, and non-shrink grouting for Compressor Train 1.",
        "discipline": "Civil & Structural",
        "weight": 0.60,
        "planned_duration": 35,
        "actual_duration": 30,
        "planned_start": "2026-06-01",
        "planned_end": "2026-07-06",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L4-02",
        "code": "WP-PLINTH-C102",
        "level": "L4",
        "parent_id": "OIL-L3-01",
        "name": "Compressor C-102 Foundation & Base Slab",
        "description": "Substructure and dynamic vibration isolation pad for Compressor Train 2.",
        "discipline": "Civil & Structural",
        "weight": 0.40,
        "planned_duration": 35,
        "actual_duration": 15,
        "planned_start": "2026-06-25",
        "planned_end": "2026-07-30",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L4-03",
        "code": "WP-LINE24-SUCT",
        "level": "L4",
        "parent_id": "OIL-L3-02",
        "name": "Line 24 Feed Gas Header 16-inch CS Piping Package",
        "description": "Main 16-inch A106 Gr.B Carbon Steel suction header connecting slug catcher to compressor manifold.",
        "discipline": "Piping & Mechanical",
        "weight": 0.50,
        "planned_duration": 40,
        "actual_duration": 20,
        "planned_start": "2026-07-01",
        "planned_end": "2026-08-10",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L4-04",
        "code": "WP-LINE12-DISCH",
        "level": "L4",
        "parent_id": "OIL-L3-02",
        "name": "Line 12 High Pressure Discharge Manifold Package",
        "description": "12-inch 600# discharge piping from compressor outlet to aftercoolers.",
        "discipline": "Piping & Mechanical",
        "weight": 0.50,
        "planned_duration": 40,
        "actual_duration": 10,
        "planned_start": "2026-07-15",
        "planned_end": "2026-08-25",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L4-05",
        "code": "WP-11KV-POWER",
        "level": "L4",
        "parent_id": "OIL-L3-03",
        "name": "11kV MV Power Distribution & Motor Feeders",
        "description": "Medium voltage cable laying from Substation-2 to Compressor Drive Motors.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.60,
        "planned_duration": 30,
        "actual_duration": 10,
        "planned_start": "2026-07-15",
        "planned_end": "2026-08-15",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },

    # ================= L5: WORK ACTIVITIES (Primavera P6 Level) =================
    {
        "id": "OIL-L5-01",
        "code": "ACT-C101-CONC",
        "level": "L5",
        "parent_id": "OIL-L4-01",
        "name": "Pour Grade M35 Reinforced Concrete for Compressor C-101 Plinth",
        "description": "Rebar binding, formwork inspection, and pour of 45 cubic meters mass concrete.",
        "discipline": "Civil & Structural",
        "weight": 0.50,
        "planned_duration": 14,
        "actual_duration": 14,
        "planned_start": "2026-06-05",
        "planned_end": "2026-06-19",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L5-02",
        "code": "ACT-C101-GROUT",
        "level": "L5",
        "parent_id": "OIL-L4-01",
        "name": "Equipment Baseplate Leveling & Non-Shrink Grouting C-101",
        "description": "Pre-grout chocking, dial indicator alignment, and epoxy grout injection.",
        "discipline": "Civil & Structural",
        "weight": 0.50,
        "planned_duration": 12,
        "actual_duration": 5,
        "planned_start": "2026-06-20",
        "planned_end": "2026-07-02",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L5-03",
        "code": "ACT-L24-SPOOL",
        "level": "L5",
        "parent_id": "OIL-L4-03",
        "name": "Erect Line 24 16-inch Carbon Steel Pipe Spool at Rack 3",
        "description": "Rigging, crane lifting, fit-up, and positional butt welding for Spool SP-24-A.",
        "discipline": "Piping & Mechanical",
        "weight": 0.60,
        "planned_duration": 18,
        "actual_duration": 8,
        "planned_start": "2026-07-01",
        "planned_end": "2026-07-19",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L5-04",
        "code": "ACT-L24-TEST",
        "level": "L5",
        "parent_id": "OIL-L4-03",
        "name": "Hydrostatic Testing Line 24 Loop-Alpha at 45 Bar",
        "description": "Flange blinding, water filling, 4-hour pressure holding, and de-watering.",
        "discipline": "Quality & Testing",
        "weight": 0.40,
        "planned_duration": 8,
        "actual_duration": 0,
        "planned_start": "2026-07-20",
        "planned_end": "2026-07-28",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },
    {
        "id": "OIL-L5-05",
        "code": "ACT-11KV-PULL",
        "level": "L5",
        "parent_id": "OIL-L4-05",
        "name": "Pull 11kV 3C x 300 sq mm Armored Cable from Substation-2",
        "description": "Cable trench tray rollers setup, drum uncoiling, pulling to motor terminal box.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.70,
        "planned_duration": 10,
        "actual_duration": 4,
        "planned_start": "2026-07-15",
        "planned_end": "2026-07-25",
        "progress_pct": 0.0,
        "status": "IN_PROGRESS",
    },

    # ================= L6: MICRO-TASKS / DAILY EXECUTABLE UNITS =================
    # Children of OIL-L5-01 (Compressor C-101 Concrete Plinth)
    {
        "id": "OIL-L6-01",
        "code": "L6-C101-REBAR",
        "level": "L6",
        "parent_id": "OIL-L5-01",
        "name": "Rebar Reinforcement Binding & Anchor Bolt Setting Plinth P-101",
        "description": "Bind Fe500D steel rebars, install template, and position 16 anchor bolts.",
        "discipline": "Civil & Structural",
        "weight": 0.40,
        "planned_duration": 5,
        "actual_duration": 5,
        "planned_start": "2026-06-05",
        "planned_end": "2026-06-10",
        "progress_pct": 100.0,
        "status": "COMPLETED",
    },
    {
        "id": "OIL-L6-02",
        "code": "L6-C101-POUR",
        "level": "L6",
        "parent_id": "OIL-L5-01",
        "name": "M35 Concrete Batching & Tremie Pouring Plinth P-101",
        "description": "Transit mixer pours, needle vibration, test cylinder casting.",
        "discipline": "Civil & Structural",
        "weight": 0.40,
        "planned_duration": 3,
        "actual_duration": 3,
        "planned_start": "2026-06-11",
        "planned_end": "2026-06-14",
        "progress_pct": 100.0,
        "status": "COMPLETED",
    },
    {
        "id": "OIL-L6-03",
        "code": "L6-C101-CURE",
        "level": "L6",
        "parent_id": "OIL-L5-01",
        "name": "Wet Curing with Hessian Cloth for Plinth P-101 Concrete",
        "description": "Continuous water ponding and curing blanket maintenance for 7 days.",
        "discipline": "Civil & Structural",
        "weight": 0.20,
        "planned_duration": 7,
        "actual_duration": 6,
        "planned_start": "2026-06-15",
        "planned_end": "2026-06-21",
        "progress_pct": 90.0,
        "status": "IN_PROGRESS",
    },

    # Children of OIL-L5-02 (Baseplate Leveling & Non-Shrink Grouting)
    {
        "id": "OIL-L6-04",
        "code": "L6-C101-SHIM",
        "level": "L6",
        "parent_id": "OIL-L5-02",
        "name": "Machine Base Shim Packing & Precision Dial Leveling C-101",
        "description": "Install precision stainless steel shims, achieve 0.05 mm/m level tolerance.",
        "discipline": "Piping & Mechanical",
        "weight": 0.50,
        "planned_duration": 6,
        "actual_duration": 3,
        "planned_start": "2026-06-20",
        "planned_end": "2026-06-26",
        "progress_pct": 50.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L6-05",
        "code": "L6-C101-EPOXY",
        "level": "L6",
        "parent_id": "OIL-L5-02",
        "name": "Epoxy Grout Mixing & Header Flow under Compressor Skid",
        "description": "Chariot mixing of Sikadur-42 grout and head-box pressure flow.",
        "discipline": "Civil & Structural",
        "weight": 0.50,
        "planned_duration": 4,
        "actual_duration": 0,
        "planned_start": "2026-06-27",
        "planned_end": "2026-07-01",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },

    # Children of OIL-L5-03 (Erect Line 24 16" CS Pipe Spool at Rack 3)
    {
        "id": "OIL-L6-06",
        "code": "L6-L24-RIG",
        "level": "L6",
        "parent_id": "OIL-L5-03",
        "name": "Crane Lifting & Positional Rigging of Spool SP-24-A at Pipe Rack 3",
        "description": "50T mobile crane lift, tag line guiding onto pipe support saddles.",
        "discipline": "Piping & Mechanical",
        "weight": 0.25,
        "planned_duration": 2,
        "actual_duration": 2,
        "planned_start": "2026-07-01",
        "planned_end": "2026-07-03",
        "progress_pct": 100.0,
        "status": "COMPLETED",
    },
    {
        "id": "OIL-L6-07",
        "code": "L6-L24-W04-FIT",
        "level": "L6",
        "parent_id": "OIL-L5-03",
        "name": "Fit-up & Root Pass TIG Welding on Joint W-04 Line 24",
        "description": "Bevel alignment, 2.5mm root gap, clamp fitting, and GTAW root pass with ER70S-6.",
        "discipline": "Piping & Mechanical",
        "weight": 0.35,
        "planned_duration": 4,
        "actual_duration": 2,
        "planned_start": "2026-07-04",
        "planned_end": "2026-07-08",
        "progress_pct": 25.0,  # Target for worker updates!
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L6-08",
        "code": "L6-L24-W04-CAP",
        "level": "L6",
        "parent_id": "OIL-L5-03",
        "name": "Hot Pass, Fill and Capping SMAW Welding on Joint W-04",
        "description": "Multi-pass SMAW welding with E7018 low-hydrogen electrodes.",
        "discipline": "Piping & Mechanical",
        "weight": 0.25,
        "planned_duration": 4,
        "actual_duration": 0,
        "planned_start": "2026-07-09",
        "planned_end": "2026-07-13",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },
    {
        "id": "OIL-L6-09",
        "code": "L6-L24-NDT-RT",
        "level": "L6",
        "parent_id": "OIL-L5-03",
        "name": "Radiographic Testing (RT) and Visual Weld Inspection Joint W-04",
        "description": "Gamma-ray radiography (Ir-192) and weld profile inspection per ASME B31.3.",
        "discipline": "Quality & Testing",
        "weight": 0.15,
        "planned_duration": 2,
        "actual_duration": 0,
        "planned_start": "2026-07-14",
        "planned_end": "2026-07-16",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },

    # Children of OIL-L5-04 (Hydrostatic Testing Line 24 Loop-Alpha)
    {
        "id": "OIL-L6-10",
        "code": "L6-L24-BLIND",
        "level": "L6",
        "parent_id": "OIL-L5-04",
        "name": "Test Blind Installation & High-Pressure Gasket Torquing",
        "description": "Install spade blinds rated for 600# ASME flanges, torque studs in star pattern.",
        "discipline": "Piping & Mechanical",
        "weight": 0.30,
        "planned_duration": 2,
        "actual_duration": 0,
        "planned_start": "2026-07-20",
        "planned_end": "2026-07-22",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },
    {
        "id": "OIL-L6-11",
        "code": "L6-L24-PRESS",
        "level": "L6",
        "parent_id": "OIL-L5-04",
        "name": "Hydrostatic Water Pressurization to 45 Bar & 4-Hour Hold",
        "description": "Pressurize system with calibrated positive displacement pump and chart recorder.",
        "discipline": "Quality & Testing",
        "weight": 0.70,
        "planned_duration": 3,
        "actual_duration": 0,
        "planned_start": "2026-07-23",
        "planned_end": "2026-07-26",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },

    # Children of OIL-L5-05 (Pull 11kV Armored Cable)
    {
        "id": "OIL-L6-12",
        "code": "L6-11KV-TRAY",
        "level": "L6",
        "parent_id": "OIL-L5-05",
        "name": "Install Cable Ladder Tray & Rollers along Bay-1 Pipe Rack",
        "description": "Heavy-duty perforated cable ladder mounting and roller positioning.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.30,
        "planned_duration": 3,
        "actual_duration": 3,
        "planned_start": "2026-07-15",
        "planned_end": "2026-07-18",
        "progress_pct": 100.0,
        "status": "COMPLETED",
    },
    {
        "id": "OIL-L6-13",
        "code": "L6-11KV-PULL",
        "level": "L6",
        "parent_id": "OIL-L5-05",
        "name": "Pull 11kV 3C x 300 sq mm XLPE Cable from Substation to C-101 Motor",
        "description": "Winch pull 280 meters continuous cable run without exceeding max tension.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.40,
        "planned_duration": 4,
        "actual_duration": 2,
        "planned_start": "2026-07-19",
        "planned_end": "2026-07-23",
        "progress_pct": 40.0,
        "status": "IN_PROGRESS",
    },
    {
        "id": "OIL-L6-14",
        "code": "L6-11KV-TERM",
        "level": "L6",
        "parent_id": "OIL-L5-05",
        "name": "Heat Shrink Termination & Hi-Pot Megger Insulation Testing",
        "description": "Raychem 11kV heat shrink kits and 25kV DC high potential insulation test.",
        "discipline": "Electrical & Instrumentation",
        "weight": 0.30,
        "planned_duration": 3,
        "actual_duration": 0,
        "planned_start": "2026-07-24",
        "planned_end": "2026-07-27",
        "progress_pct": 0.0,
        "status": "NOT_STARTED",
    },
]

INITIAL_CHAT_MESSAGES = [
    {
        "channel": "field-updates",
        "sender_name": "R. K. Baruah",
        "sender_role": "L1_DIRECTOR",
        "message_text": "Team, prioritize Compressor C-101 plinth curing and Line 24 spool welding. We need gas manifold ready for commissioning next month.",
        "is_field_update": 0,
        "linked_task_id": None,
        "confidence_score": None,
        "timestamp": "2026-07-06 08:30:00",
    },
    {
        "channel": "field-updates",
        "sender_name": "Debashis Phukan",
        "sender_role": "L3_DISCIPLINE_LEAD",
        "message_text": "Noted Director. Civil plinth is 90% cured. Piping crew has mobilized crane for Line 24 spool at Rack 3.",
        "is_field_update": 0,
        "linked_task_id": None,
        "confidence_score": None,
        "timestamp": "2026-07-06 09:15:00",
    },
    {
        "channel": "field-updates",
        "sender_name": "Pranab Saikia",
        "sender_role": "L5_SITE_SUPERVISOR",
        "message_text": "Spool SP-24-A lifted and placed on rack. Root pass started on Joint W-04, 25% completed.",
        "is_field_update": 1,
        "linked_task_id": "OIL-L6-07",
        "confidence_score": 92.5,
        "timestamp": "2026-07-06 14:20:00",
    },
]
